### ISSUE TITLE
Chore: 프로젝트 초기 설정

### ISSUE THREAD

**Issue by joshuayeyo** [joshuayeyo/suika#1]
## Description
프로젝트 초기 설정

## Todo
- [ ] [Matter.js](https://brm.io/matter-js/) 설치
- [ ] Prettier, ESLint 설치
- [ ] emotoion/styled 설치
